### ISSUE TITLE
Password to root user is exposed

### ISSUE THREAD

**Issue by twaritwaikar** [krypton08rises/EMS-IMARC#1]
https://github.com/krypton08rises/EMS-IMARC/blob/b44904f2e94fd0dae945db9126426f507b723fda/EMS-IMARC/Includes/config.php#L5

Reminder: Do not push config files containing your local MySQL passwords to Github. Now that this has been pushed, you may have to add this to gitignore and change your MySQL root user password.

**Comment by krypton08rises** [comment]
This is the password of the localhost hosted on xampp server, it is default in every localhost, so you can't access my local database.
